restaurants = [
    {"name": "台乡缘", "cuisine": "台州菜", "location": "外滩", "recommendations": ["杂鱼", "沙蒜豆面"]},
    {"name": "债晶", "cuisine": "台州菜", "location": "外滩", "recommendations": ["豆腐鱼", "肉燕汤"]},
    {"name": "柿合缘", "cuisine": "甬府旗下", "location": "国金", "recommendations": ["鱼头配油条", "炙子羊肉"]},
    {"name": "荣家黄鱼面", "cuisine": "海鲜", "recommendations": ["姜汤面"]},
    {"name": "荣小馆", "cuisine": "海鲜", "recommendations": ["东海杂鱼", "脆炸乳鲍", "临海扇食", "黄鱼烧年糕", "密汁红薯"]},
    {"name": "人逸道", "cuisine": "淮扬菜", "recommendations": ["天目竹笋干红烧肉", "龙虾炒年糕", "金陵烤鸭", "陈皮红豆"]},
    {"name": "晟永兴", "cuisine": "烤鸭", "location": "富士康大楼", "recommendations": ["烤鸭", "乾隆白菜", "牛肉", "羊肉"]},
    {"name": "隆台", "cuisine": "台州菜", "recommendations": ["海鲜", "炒饭"]},
    {"name": "喜粤八号", "cuisine": "粤菜", "recommendations": ["平价米其林"]},
    {"name": "barbarian", "cuisine": "烧烤", "location": "武定路", "recommendations": ["不文明夫妇套餐"]},
    {"name": "铁屋", "cuisine": "日式烤肉", "location": "古北", "recommendations": ["日式烤肉"]},
    {"name": "逸谷会", "cuisine": "工作餐", "location": "浦东嘉里城", "recommendations": ["鱼头汤", "脆皮鸡", "糟卤四宝", "红烧肉", "咸肉菜饭"]},
    {"name": "食访", "cuisine": "工作餐", "location": "浦东嘉里城", "recommendations": ["狮子头", "烟蚂黄鱼", "葱油嫩鸡", "醉八仙"]},
    {"name": "泰珍葵", "cuisine": "泰国菜", "recommendations": ["冬阴功汤", "各种烤肉"]},
    {"name": "Hakkasan", "cuisine": "高端粤式", "recommendations": ["各种鱼子"]},
    {"name": "誉八仙", "cuisine": "粤式", "location": "新天地", "recommendations": ["靓汤", "传统点心"]},
    {"name": "御宝轩", "cuisine": "粤式", "location": "外滩", "recommendations": ["点心", "汤", "福建炒饭"]},
    {"name": "klay", "cuisine": "咖喱", "recommendations": ["咖喱"]},
    {"name": "赣江村", "cuisine": "江西菜", "recommendations": ["辣味"]},
    {"name": "竹屋", "cuisine": "川菜", "recommendations": ["炒鸡杂", "毛血旺", "江油肥肠", "辣子鸡"]},
    {"name": "10'mils", "cuisine": "brunch", "location": "音乐学院附近", "recommendations": ["早餐"]},
    {"name": "BOR", "cuisine": "brunch", "location": "安福路", "recommendations": ["烤章鱼脚", "烟玛猪肋排", "烤虾配柚子", "香前扇贝配鱼子"]},
    {"name": "bistro11", "cuisine": "brunch", "recommendations": ["早午餐"]},
    {"name": "Polux by Paul Pairet", "cuisine": "西餐", "location": "新天地", "recommendations": ["牛肉塔塔", "牛排", "忽肝着派"]},
    {"name": "calypso", "cuisine": "地中海菜", "location": "静安香格里拉", "recommendations": ["烤鳃鱼", "煎扇贝", "披萨"]},
    {"name": "Bella napoli", "cuisine": "西西里餐厅", "location": "长乐路", "recommendations": ["披萨", "火腿拼盘", "意面", "海鲈鱼"]},
    {"name": "Mercato by Jean Georges", "cuisine": "商务西餐", "recommendations": ["米其林水准"]},
    {"name": "张爪爪贵州油灿鸡", "cuisine": "贵州菜", "recommendations": ["油灿鸡"]},
    {"name": "亲亲长沙米粉", "cuisine": "湖南米粉", "recommendations": ["白辣椒肉丝粉"]},
    {"name": "334 BIRD HUT", "cuisine": "海南鸡饭", "location": "泰兴路", "recommendations": ["残油鸡饭", "海南鸡饭"]},
    {"name": "潮兴肠粉店", "cuisine": "潮汕菜", "recommendations": ["肠粉", "卤味套餐"]},
    {"name": "伊祥敦煌楼", "cuisine": "西北菜", "recommendations": ["牛肉面", "烤串"]},
    {"name": "快活湖南粉馆", "cuisine": "湖南米粉", "recommendations": ["米粉"]},
    {"name": "温州海鲜黄牛馆", "cuisine": "温州菜", "location": "大统路", "recommendations": ["海鲜"]},
    {"name": "纪州豚骨效油拉面", "cuisine": "日式拉面", "recommendations": ["拉面"]},
    {"name": "bpeefman", "cuisine": "西式", "recommendations": ["牛肉饼"]},
    {"name": "江西客家传统小炒", "cuisine": "江西菜", "recommendations": ["小炒"]},
    {"name": "潮人姐妹轩", "cuisine": "潮汕菜", "recommendations": ["生腌"]},
    {"name": "Garlic Barbecue", "cuisine": "烧烤", "recommendations": ["澳洲牛胸肉", "猪排小汉堡"]},
    {"name": "惠食佳", "cuisine": "粤式", "location": "人民广场", "recommendations": ["嗜嗜煲", "甜品"]},
    {"name": "柴米多", "cuisine": "改良菜", "recommendations": ["披萨", "香肠拼盘", "包浆豆腐", "火腿铜锅饭"]},
    {"name": "photoshop", "cuisine": "越南菜", "location": "武定路", "recommendations": ["越南河粉"]},
    {"name": "滇道", "cuisine": "云南菜", "location": "康定路", "recommendations": ["大救加", "老奶洋芋", "豆花米线"]},
    {"name": "bottega", "cuisine": "披萨", "recommendations": ["披萨"]},
    {"name": "mamamia", "cuisine": "披萨", "recommendations": ["披萨"]},
    {"name": "mbd", "cuisine": "面包", "recommendations": ["小面包"]}
]